-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Employees"
(
    employee_id bigint NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    data_of_bithday date NOT NULL,
    gender text NOT NULL,
    phone_number character varying(13) NOT NULL,
    email character varying(50) NOT NULL,
    addres text NOT NULL,
    "position" text NOT NULL,
    family_phone_number character varying(13) NOT NULL,
    create_at time with time zone NOT NULL,
    update_at time with time zone,
    salary real NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public."Costumer"
(
    "Constumer_id" bigint NOT NULL,
    "Phone_number" character varying(15) NOT NULL,
    PRIMARY KEY ("Constumer_id")
);

CREATE TABLE IF NOT EXISTS public."Orders"
(
    order_id bigint NOT NULL,
    costumer_id bigint NOT NULL,
    order_date date NOT NULL,
    total_amount real NOT NULL,
    status text,
    table_id bigint NOT NULL,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.order_items
(
    order_item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    "Product_id" bigint NOT NULL,
    quantity smallint NOT NULL,
    "UnitPrice" real,
    PRIMARY KEY (order_item_id)
);

CREATE TABLE IF NOT EXISTS public."Tables"
(
    table_id bigint NOT NULL,
    table_number bigint NOT NULL,
    seating_capacity smallint NOT NULL,
    status text NOT NULL,
    PRIMARY KEY (table_id)
);

CREATE TABLE IF NOT EXISTS public."Served_items"
(
    "Served_item_id" bigint NOT NULL,
    order_item_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    served_data date NOT NULL,
    served_time time with time zone NOT NULL,
    PRIMARY KEY ("Served_item_id")
);

CREATE TABLE IF NOT EXISTS public."Chef"
(
    chef_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    order_id bigint NOT NULL,
    PRIMARY KEY (chef_id)
);

CREATE TABLE IF NOT EXISTS public."Products"
(
    "Producr_id" bigint NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    price real NOT NULL,
    is_aviable bigint NOT NULL,
    catigory text NOT NULL,
    PRIMARY KEY ("Producr_id")
);

ALTER TABLE IF EXISTS public."Orders"
    ADD FOREIGN KEY (costumer_id)
    REFERENCES public."Costumer" ("Constumer_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders"
    ADD FOREIGN KEY (table_id)
    REFERENCES public."Tables" (table_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_items
    ADD FOREIGN KEY (order_id)
    REFERENCES public."Orders" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_items
    ADD FOREIGN KEY ("Product_id")
    REFERENCES public."Products" ("Producr_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Served_items"
    ADD FOREIGN KEY (order_item_id)
    REFERENCES public.order_items (order_item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Served_items"
    ADD FOREIGN KEY (employee_id)
    REFERENCES public."Employees" (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Chef"
    ADD FOREIGN KEY (order_id)
    REFERENCES public."Orders" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Chef"
    ADD FOREIGN KEY (employee_id)
    REFERENCES public."Employees" (employee_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;